---

- hosts: localhost
  name: Install and config neovim
  connection: local
  become: true
  tasks:

    - name: Install packages
      apt:
        name: "{{ item }}"
      loop: "{{ packages }}"

    - name: Install composer
      ansible.builtin.shell: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
        mv composer.phar /usr/local/bin/composer
       
    - name: Download neovim
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/download/v0.9.2/nvim.appimage
        dest: /usr/bin/nvim
        mode: 655

    - name: Download phpactor
      ansible.builtin.get_url:
        url: https://github.com/phpactor/phpactor/releases/latest/download/phpactor.phar
        dest: /usr/local/bin/phpactor
        mode: 655
    
    # - name: Check if nvim config folder exits
    #   ansible.builtin.stat:
    #     path: "/home/{{ item }}/.config/nvim/lua/"
    #   register: file_data
    #   loop: "{{ users }}"
    #
    # - name: Backup nvim config dir
    #   ansible.builtin.command:
    #     cmd: mv "/home/{{ item.item }}/.config/nvim" "/home/{{ item.item }}/.config/nvim_bck"
    #   when: item.stat.exists
    #   loop: "{{ file_data.results }}"

    - name: Ensure ~/.config/nvim exists
      ansible.builtin.file:
        path: "/home/{{ item }}/.config/nvim/lua"
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: "0775"
        recurse: true
      loop: "{{ users }}"

    - name: Copy init.lua
      ansible.builtin.copy:
        src: init.lua
        dest: "/home/{{ item }}/.config/nvim/"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: "0644"
      loop: "{{ users }}"

    - name: Copy lua files
      ansible.builtin.copy:
        src: lua/
        dest: "/home/{{ item }}/.config/nvim/lua/"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: "0644"
      loop: "{{ users }}"
